'''User input'''
print()
print('Star wars Mad Lib Activity\n')
print('please enter a word in the following sections:\n')
Noun_1 = input('Noun = ')
Noun_2 = input('Noun = ')
noun_3 = input('Noun = ')
Adj_1 = input('Adjective(shape) = ')
adj_2 = input('Adjective = ')
noun_lrg_obj = input('Noun(large object) = ')
noun_4 = input('Noun = ')
adj_3 = input('Adjective = ')
verb_1 = input('Verb = ')
adj_4 = input('Adjective = ')
noun_5 = input('Noun = ')

print()
print('Here is your Star Wars story!:')
print()

'''Display output'''
print('The Death Star is a ' + Noun_1 + ' and super-' + Noun_2)
print('built by the Galactic ' + noun_3 + '. A Death Star')
print('is ' + Adj_1 + ' shaped and is so ' + adj_2 + ' that it')
print('is the size of a ' + noun_lrg_obj + '. This ' + noun_4 + ' is so ')
print(adj_3 + ' it can ' + verb_1 + ' an entire planet with')
print('its ' + adj_4 + ' ' + noun_5 + '.')
print()